### ISSUE TITLE
E5000: Cannot form a matching secure hash based on the merchant's request using either of the two merchant's secrets

### ISSUE THREAD

**Issue by FatenElhariry** [JustCallMeAD/MIGS-payment-gateway-MVC5#3]
what is the problem here i supposed that because  i work in local not publish system ??

**Comment by JustCallMeAD** [comment]
You must publish this project to a live domain so that Mastercard can return a result to your website after they have attempted to process your payment.

**Comment by FatenElhariry** [comment]
if i not publish it what the problem
